version: 2

jobs:
  build:
    docker:
      -image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      
      - run: npm install
      
      - run:
          command: ./node_modules/.bin/firebase deploy --token="1/krA1qzdhmoRFvjQOYYft_JR-w4okRH-t1R4_1q141RQ"
  