version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - run:
          name: Show current directory
          command: pwd

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules

      - run:
          name: Install Angular CLI
          command: sudo npm install -g @angular/cli

      - run:
          name: Show Angular version
          command: ng version

      - run: 
          name: Building
          command: ng build --prod=true

      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist
              - package.json
              - firebase.json
              - .firebaserc

      # - run:
      #     command: ./node_modules/.bin/firebase deploy --token="1/krA1qzdhmoRFvjQOYYft_JR-w4okRH-t1R4_1q141RQ"
  
  deploy: 
    docker:
      - image: circleci/node:10.15
    
    working_directory: ~/repo
    steps:
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}

      - restore_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      
      - run:
        name: Install Firebase
        command: npm install --save-dev firebase-tools

      - run:
        name: Deploy to Firebase
        command: ./node_modules/.bin/firebase deploy --token="1/krA1qzdhmoRFvjQOYYft_JR-w4okRH-t1R4_1q141RQ"

workflows:
    version: 2
    -deploy:
        jobs:
        - build:
            filters:
                branches:
                    only: master
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
